theme: jekyll-theme-architect
title: "Graph.js"
description: "SVG graphs controlled by JavaScript"
show_downloads: true
github:
  ts_url: "graph.ts"
  js_url: "graph.js"
  tsx_url: "graph.tsx"
  jsx_url: "graph.jsx"
logo: "logo.png"
